// includes
//Fonts
/*
ACaslonPro-Bold,ACaslonPro-BoldItalic,ACaslonPro-BoldItalic,ACaslonPro-Italic,ACaslonPro-Regular,ACaslonPro-Semibold,ACaslonPro-SemiboldItalic,ADMUI3,AdobeArabic-Bold,AdobeArabic-Bold
ACaslonPro-Bold.otf 
ACaslonPro-BoldItalic.otf 
ACaslonPro-Italic.otf 
ACaslonPro-Regular.otf 
ACaslonPro-Semibold.otf 
ACaslonPro-SemiboldItalic.otf 
ADMUI3.fon 
AdobeArabic-Bold.otf 
AdobeArabic-BoldItalic.otf 
AdobeArabic-Italic.otf 
AdobeArabic-Regular.otf 
AdobeFangsongStd-Regular.otf 
AdobeFanHeitiStd-Bold.otf 
AdobeGothicStd-Bold.otf 
AdobeHebrew-Bold.otf 
AdobeHebrew-BoldItalic.otf 
AdobeHebrew-Italic.otf 
AdobeHebrew-Regular.otf 
AdobeHeitiStd-Regular.otf 
AdobeKaitiStd-Regular.otf 
AdobeMingStd-Light.otf 
AdobeMyungjoStd-Medium.otf 
AdobeSongStd-Light.otf 
AGaramondPro-Bold.otf 
AGaramondPro-BoldItalic.otf 
AGaramondPro-Italic.otf 
AGaramondPro-Regular.otf 
AGENCYB.TTF 
AGENCYR.TTF 
AHROB.TTF 
ahronbd.ttf 
ALGER.TTF 
andlso.ttf 
angsa.ttf 
angsab.ttf 
angsai.ttf 
angsau.ttf 
angsaub.ttf 
angsaui.ttf 
angsauz.ttf 
angsaz.ttf 
ANTQUAB.TTF 
ANTQUABI.TTF 
ANTQUAI.TTF 
aparaj.ttf 
aparajb.ttf 
aparajbi.ttf 
aparaji.ttf 
app850.fon 
arabtype.ttf 
ARAM.TTF 
arial.ttf 
arialbd.ttf 
arialbi.ttf 
ariali.ttf 
ARIALN.TTF 
ARIALNB.TTF 
ARIALNBI.TTF 
ARIALNI.TTF 
ARIALUNI.TTF 
ariblk.ttf 
ARLRDBD.TTF 
BASKVILL.TTF 
batang.ttc 
batch.bat 
BAUHS93.TTF 
BELL.TTF 
BELLB.TTF 
BELLI.TTF 
BERNHC.TTF 
BirchStd.otf 
BKANT.TTF 
BlackoakStd.otf 
BOD_B.TTF 
BOD_BI.TTF 
BOD_BLAI.TTF 
BOD_BLAR.TTF 
BOD_CB.TTF 
BOD_CBI.TTF 
BOD_CI.TTF 
BOD_CR.TTF 
BOD_I.TTF 
BOD_PSTC.TTF 
BOD_R.TTF 
BOOKOS.TTF 
BOOKOSB.TTF 
BOOKOSBI.TTF 
BOOKOSI.TTF 
BRADHITC.TTF 
BRITANIC.TTF 
BRLNSB.TTF 
BRLNSDB.TTF 
BRLNSR.TTF 
BROADW.TTF 
browa.ttf 
browab.ttf 
browai.ttf 
browau.ttf 
browaub.ttf 
browaui.ttf 
browauz.ttf 
browaz.ttf 
BRUSHSCI.TTF 
BrushScriptStd.otf 
calibri.ttf 
calibrib.ttf 
calibrii.ttf 
calibriz.ttf 
CALIFB.TTF 
CALIFI.TTF 
CALIFR.TTF 
CALIG.TTF 
CALIST.TTF 
CALISTB.TTF 
CALISTBI.TTF 
CALISTI.TTF 
cambria.ttc 
cambriab.ttf 
cambriai.ttf 
cambriaz.ttf 
Candara.ttf 
Candarab.ttf 
Candarai.ttf 
Candaraz.ttf 
CASTELAR.TTF 
CENSCBK.TTF 
CENTAUR.TTF 
CENTURY.TTF 
ChaparralPro-Bold.otf 
ChaparralPro-BoldIt.otf 
ChaparralPro-Italic.otf 
ChaparralPro-Regular.otf 
CharlemagneStd-Bold.otf 
CHILLER.TTF 
COLONNA.TTF 
comic.ttf 
comicbd.ttf 
consola.ttf 
consolab.ttf 
consolai.ttf 
consolaz.ttf 
constan.ttf 
constanb.ttf 
constani.ttf 
constanz.ttf 
COOPBL.TTF 
CooperBlackStd-Italic.otf 
CooperBlackStd.otf 
COPRGTB.TTF 
COPRGTL.TTF 
corbel.ttf 
corbelb.ttf 
corbeli.ttf 
corbelz.ttf 
cordia.ttf 
cordiab.ttf 
cordiai.ttf 
cordiau.ttf 
cordiaub.ttf 
cordiaui.ttf 
cordiauz.ttf 
cordiaz.ttf 
cour.ttf 
courbd.ttf 
courbi.ttf 
coure.fon 
couri.ttf 
CURLZ___.TTF 
daunpenh.ttf 
david.ttf 
DAVIDB.TTF 
davidbd.ttf 
DAVIDL.TTF 
DejaVuSans-Bold.ttf 
DejaVuSans-BoldOblique.ttf 
DejaVuSans-ExtraLight.ttf 
DejaVuSans-Oblique.ttf 
DejaVuSans.ttf 
DejaVuSansCondensed-Bold.ttf 
DejaVuSansCondensed-BoldOblique.ttf 
DejaVuSansCondensed-Oblique.ttf 
DejaVuSansCondensed.ttf 
DejaVuSansMono-Bold.ttf 
DejaVuSansMono-BoldOblique.ttf 
DejaVuSansMono-Oblique.ttf 
DejaVuSansMono.ttf 
DejaVuSerif-Bold.ttf 
DejaVuSerif-BoldItalic.ttf 
DejaVuSerif-Italic.ttf 
DejaVuSerif.ttf 
DejaVuSerifCondensed-Bold.ttf 
DejaVuSerifCondensed-BoldItalic.ttf 
DejaVuSerifCondensed-Italic.ttf 
DejaVuSerifCondensed.ttf 
dokchamp.ttf 
DROGB.TTF 
DROGM.TTF 
ebrima.ttf 
ebrimabd.ttf 
ELEPHNT.TTF 
ELEPHNTI.TTF 
ENGR.TTF 
ERASBD.TTF 
ERASDEMI.TTF 
ERASLGHT.TTF 
ERASMD.TTF 
estre.ttf 
euphemia.ttf 
FELIXTI.TTF 
FORTE.TTF 
FRABK.TTF 
FRABKIT.TTF 
FRADM.TTF 
FRADMCN.TTF 
FRADMIT.TTF 
FRAHV.TTF 
FRAHVIT.TTF 
framd.ttf 
FRAMDCN.TTF 
framdit.ttf 
frank.ttf 
FRANKB.TTF 
FREESCPT.TTF 
FRNEW.TTF 
FRSCRIPT.TTF 
FTLTLT.TTF 
Gabriola.ttf 
GADII.TTF 
GADIL.TTF 
GAHROM.TTF 
GARA.TTF 
GARABD.TTF 
GARAIT.TTF 
gautami.ttf 
gautamib.ttf 
GDAVID.TTF 
GenBasB.ttf 
GenBasBI.ttf 
GenBasI.ttf 
GenBasR.ttf 
GenBkBasB.ttf 
GenBkBasBI.ttf 
GenBkBasI.ttf 
GenBkBasR.ttf 
georgia.ttf 
georgiab.ttf 
georgiai.ttf 
georgiaz.ttf 
GFRANK.TTF 
GHAIM.TTF 
GHAIMC.TTF 
GiddyupStd.otf 
GIGI.TTF 
GILBI___.TTF 
GILB____.TTF 
GILC____.TTF 
GILI____.TTF 
GILLUBCD.TTF 
GILSANUB.TTF 
GIL_____.TTF 
gisha.ttf 
gishabd.ttf 
GKAVBLD.TTF 
GKAVLIT.TTF 
GKAVMED.TTF 
GLECB.TTF 
GLSNECB.TTF 
GMYAMFIX.TTF 
GOTHIC.TTF 
GOTHICB.TTF 
GOTHICBI.TTF 
GOTHICI.TTF 
GOUDOS.TTF 
GOUDOSB.TTF 
GOUDOSI.TTF 
GOUDYSTO.TTF 
gulim.ttc 
GYADBR.TTF 
GYADL.TTF 
GYADXL.TTF 
HARLOWSI.TTF 
HARNGTON.TTF 
HATTEN.TTF 
HDAS.TTF 
HDASBD.TTF 
himalaya.ttf 
HoboStd.otf 
HODES.TTF 
HODESB.TTF 
HODESL.TTF 
HTOWERT.TTF 
HTOWERTI.TTF 
impact.ttf 
IMPRISHA.TTF 
INFROMAN.TTF 
iskpota.ttf 
iskpotab.ttf 
ITCBLKAD.TTF 
ITCEDSCR.TTF 
ITCKRIST.TTF 
JOKERMAN.TTF 
JUICE___.TTF 
kaiu.ttf 
kalinga.ttf 
kalingab.ttf 
kartika.ttf 
kartikab.ttf 
KERENB.TTF 
KERENM.TTF 
KhmerUI.ttf 
KhmerUIb.ttf 
kokila.ttf 
kokilab.ttf 
kokilabi.ttf 
kokilai.ttf 
KozGoPr6N-Bold.otf 
KozGoPr6N-ExtraLight.otf 
KozGoPr6N-Heavy.otf 
KozGoPr6N-Light.otf 
KozGoPr6N-Medium.otf 
KozGoPr6N-Regular.otf 
KozGoPro-Bold.otf 
KozGoPro-ExtraLight.otf 
KozGoPro-Heavy.otf 
KozGoPro-Light.otf 
KozGoPro-Medium.otf 
KozGoPro-Regular.otf 
KozMinPr6N-Bold.otf 
KozMinPr6N-ExtraLight.otf 
KozMinPr6N-Heavy.otf 
KozMinPr6N-Light.otf 
KozMinPr6N-Medium.otf 
KozMinPr6N-Regular.otf 
KozMinPro-Bold.otf 
KozMinPro-ExtraLight.otf 
KozMinPro-Heavy.otf 
KozMinPro-Light.otf 
KozMinPro-Medium.otf 
KozMinPro-Regular.otf 
KUNSTLER.TTF 
LaoUI.ttf 
LaoUIb.ttf 
latha.ttf 
lathab.ttf 
LATINWD.TTF 
LBRITE.TTF 
LBRITED.TTF 
LBRITEDI.TTF 
LBRITEI.TTF 
LCALLIG.TTF 
leelawad.ttf 
leelawdb.ttf 
LetterGothicStd-Bold.otf 
LetterGothicStd-BoldSlanted.otf 
LetterGothicStd-Slanted.otf 
LetterGothicStd.otf 
LFAX.TTF 
LFAXD.TTF 
LFAXDI.TTF 
LFAXI.TTF 
LHANDW.TTF 
LithosPro-Black.otf 
LithosPro-Regular.otf 
LOGO1.TTF 
LSANS.TTF 
LSANSD.TTF 
LSANSDI.TTF 
LSANSI.TTF 
LTYPE.TTF 
LTYPEB.TTF 
LTYPEBO.TTF 
LTYPEO.TTF 
lucon.ttf 
lvnm.ttf 
lvnmbd.ttf 
l_10646.ttf 
MAGNETOB.TTF 
MAIAN.TTF 
majalla.ttf 
majallab.ttf 
malgun.ttf 
malgunbd.ttf 
mangal.ttf 
mangalb.ttf 
MANTB.TTF 
MANTDEC.TTF 
MANTM.TTF 
MATURASC.TTF 
meiryo.ttc 
meiryob.ttc 
MesquiteStd.otf 
micross.ttf 
mingliu.ttc 
mingliub.ttc 
MinionPro-Bold.otf 
MinionPro-BoldCn.otf 
MinionPro-BoldCnIt.otf 
MinionPro-BoldIt.otf 
MinionPro-It.otf 
MinionPro-Medium.otf 
MinionPro-MediumIt.otf 
MinionPro-Regular.otf 
MinionPro-Semibold.otf 
MinionPro-SemiboldIt.otf 
MIRB.TTF 
MIRFX.TTF 
MIRL.TTF 
MISTRAL.TTF 
MOD20.TTF 
modern.fon 
monbaiti.ttf 
moolbor.ttf 
mriam.ttf 
mriamc.ttf 
msgothic.ttc 
msjh.ttf 
msjhbd.ttf 
msmincho.ttc 
msuighur.ttf 
msyh.ttf 
msyhbd.ttf 
msyi.ttf 
MTCORSVA.TTF 
mvboli.ttf 
MyriadPro-Bold.otf 
MyriadPro-BoldCond.otf 
MyriadPro-BoldCondIt.otf 
MyriadPro-BoldIt.otf 
MyriadPro-Cond.otf 
MyriadPro-CondIt.otf 
MyriadPro-It.otf 
MyriadPro-Regular.otf 
MyriadPro-Semibold.otf 
MyriadPro-SemiboldIt.otf 
MyriadWebPro-Bold.ttf 
MyriadWebPro-Italic.ttf 
MyriadWebPro.ttf 
NIAGENG.TTF 
NIAGSOL.TTF 
nrkis.ttf 
ntailu.ttf 
ntailub.ttf 
NuevaStd-BoldCond.otf 
NuevaStd-BoldCondItalic.otf 
NuevaStd-Cond.otf 
NuevaStd-CondItalic.otf 
nyala.ttf 
OCRAEXT.TTF 
OCRAStd.otf 
OLDENGL.TTF 
ONYX.TTF 
opens___.ttf 
OratorStd-Slanted.otf 
OratorStd.otf 
pala.ttf 
palab.ttf 
palabi.ttf 
palai.ttf 
PALSCRI.TTF 
PAPYRUS.TTF 
PARCHM.TTF 
PERBI___.TTF 
PERB____.TTF 
PERI____.TTF 
PERTIBD.TTF 
PERTILI.TTF 
PER_____.TTF 
phagspa.ttf 
phagspab.ttf 
plantc.ttf 
PLAYBILL.TTF 
POORICH.TTF 
PoplarStd.otf 
PrestigeEliteStd-Bd.otf 
PRISTINA.TTF 
raavi.ttf 
raavib.ttf 
RAGE.TTF 
RASHI.TTF 
RASHIB.TTF 
RAVIE.TTF 
ROCCB___.TTF 
ROCC____.TTF 
ROCK.TTF 
ROCKB.TTF 
ROCKBI.TTF 
ROCKEB.TTF 
ROCKI.TTF 
rod.ttf 
roman.fon 
RosewoodStd-Regular.otf 
SCHLBKB.TTF 
SCHLBKBI.TTF 
SCHLBKI.TTF 
script.fon 
SCRIPTBL.TTF 
segoepr.ttf 
segoeprb.ttf 
segoesc.ttf 
segoescb.ttf 
segoeui.ttf 
segoeuib.ttf 
segoeuii.ttf 
segoeuil.ttf 
segoeuiz.ttf 
seguisb.ttf 
seguisym.ttf 
serife.fon 
Shonar.ttf 
Shonarb.ttf 
SHOWG.TTF 
shruti.ttf 
shrutib.ttf 
simfang.ttf 
simhei.ttf 
simkai.ttf 
simpbdo.ttf 
simpfxo.ttf 
simpo.ttf 
simsun.ttc 
simsunb.ttf 
smalle.fon 
SNAP____.TTF 
SONC.TTF 
SONCB.TTF 
SONCL.TTF 
sserife.fon 
STAM.TTF 
STAM1.TTF 
STENCIL.TTF 
StencilStd.otf 
sylfaen.ttf 
symbol.ttf 
tahoma.ttf 
tahomabd.ttf 
taile.ttf 
taileb.ttf 
TCBI____.TTF 
TCB_____.TTF 
TCCB____.TTF 
TCCEB.TTF 
TCCM____.TTF 
TCMI____.TTF 
TCM_____.TTF 
TektonPro-Bold.otf 
TektonPro-BoldCond.otf 
TektonPro-BoldExt.otf 
TektonPro-BoldObl.otf 
TEMPSITC.TTF 
times.ttf 
timesbd.ttf 
timesbi.ttf 
timesi.ttf 
TOLB.TTF 
TOLM.TTF 
tradbdo.ttf 
trado.ttf 
TrajanPro-Bold.otf 
TrajanPro-Regular.otf 
trebuc.ttf 
trebucbd.ttf 
trebucbi.ttf 
trebucit.ttf 
tunga.ttf 
tungab.ttf 
TZVIB.TTF 
TZVIM.TTF 
upcdb.ttf 
upcdbi.ttf 
upcdi.ttf 
upcdl.ttf 
upceb.ttf 
upcebi.ttf 
upcei.ttf 
upcel.ttf 
upcfb.ttf 
upcfbi.ttf 
upcfi.ttf 
upcfl.ttf 
upcib.ttf 
upcibi.ttf 
upcii.ttf 
upcil.ttf 
upcjb.ttf 
upcjbi.ttf 
upcji.ttf 
upcjl.ttf 
upckb.ttf 
upckbi.ttf 
upcki.ttf 
upckl.ttf 
upclb.ttf 
upclbi.ttf 
upcli.ttf 
upcll.ttf 
utsaah.ttf 
utsaahb.ttf 
utsaahbi.ttf 
utsaahi.ttf 
Vani.ttf 
Vanib.ttf 
verdana.ttf 
verdanab.ttf 
verdanai.ttf 
verdanaz.ttf 
vga850.fon 
vgafix.fon 
vgasys.fon 
vijaya.ttf 
vijayab.ttf 
VILNA.TTF 
VILNAB.TTF 
VINERITC.TTF 
VIVALDII.TTF 
VLADIMIR.TTF 
vrinda.ttf 
vrindab.ttf 
webdings.ttf 
wingding.ttf 
WINGDNG2.TTF 
WINGDNG3.TTF 

*/
CreateClientConVar("ch_font_size",20,false,false) // default
Font = {"Arial","Coolvetica","ACaslonPro-Bold","ACaslonPro-BoldItalic","ACaslonPro-BoldItalic","ACaslonPro-Italic","ACaslonPro-Regular","ACaslonPro-Semibold","ACaslonPro-SemiboldItalic","ADMUI3","AdobeArabic-Bold","AdobeArabic-Bold"}
/*
surface.CreateFont("arial", 20, 400, true, false, "Arial")
surface.CreateFont ("coolvetica", 20, 400, true, false, "Coolvetica")
*/

for k, name in ipairs(Font) do
surface.CreateFont(name,12,350,true,false,name)
end

